
spring:
  datasource:
    url: jdbc:h2:mem:dressmakerdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      generate-statistics: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect      
  h2:
    console:
      enabled: true
      path: /h2console

server:
  port: 8888
  
  
